import { useEffect,useState } from "react";
import { Link } from "react-router-dom";
import { ItemCard } from "../components/ItemCard";
import { EmptyState,ErrorMessage,LoadingState } from "../components/PageState";
import { useAuth } from "../context/AuthContext";
import { api } from "../services/api";

const list=(d,k)=>Array.isArray(d)?d:d?.[k]||[];

export function DashboardPage(){
  const{token,user}=useAuth();const[items,setItems]=useState([]),[claims,setClaims]=useState([]),[received,setReceived]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[claimError,setClaimError]=useState("");
  async function load(){setLoading(true);setError("");const r=await Promise.allSettled([api.getMyItems(token),api.getMyClaims(token),api.getReceivedClaims(token)]);if(r[0].status==="fulfilled")setItems(list(r[0].value,"items"));else setError(r[0].reason.message);if(r[1].status==="fulfilled")setClaims(list(r[1].value,"claims"));if(r[2].status==="fulfilled")setReceived(list(r[2].value,"claims"));setLoading(false)}
  useEffect(()=>{load()},[token]);
  async function update(id,status){setClaimError("");try{await api.updateClaimStatus(id,status,token);await load()}catch(e){setClaimError(e.message)}}
  async function del(id){if(!window.confirm("Delete this listing?"))return;try{await api.deleteItem(id,token);await load()}catch(e){setError(e.message)}}
  return <section className="section"><div className="container"><div className="dashboard-header"><div><span className="eyebrow">Your account</span><h1>Hi, {user?.name||"there"}.</h1><p className="section-copy">Manage your listings and claim activity.</p></div><div className="hero-actions"><Link className="button button-small" to="/report/lost">Report lost</Link><Link className="button button-secondary button-small" to="/report/found">Report found</Link></div></div>{loading?<LoadingState label="Loading dashboard…" />:<>{error&&<ErrorMessage>{error}</ErrorMessage>}<section className="dashboard-section"><div className="section-heading"><div><span className="eyebrow">Listings</span><h2>My items</h2></div></div>{items.length?<div className="item-grid">{items.map(i=><div key={i._id} className="dashboard-item"><ItemCard item={i}/><div className="dashboard-item-actions"><Link className="text-link" to={`/items/${i._id}/edit`}>Edit</Link><button className="link-button danger-link" onClick={()=>del(i._id)}>Delete</button></div></div>)}</div>:<EmptyState title="You haven't posted anything yet"><Link className="text-link" to="/report/lost">Create your first listing.</Link></EmptyState>}</section><section className="dashboard-section"><div className="section-heading"><div><span className="eyebrow">Requests</span><h2>My claims</h2></div></div>{claimError&&<ErrorMessage>{claimError}</ErrorMessage>}{claims.length?<div className="claim-list">{claims.map(c=><div className="claim-row" key={c._id}><div><strong>{c.item?.title||"Item"}</strong><p>{c.item?.type||"Listing"}</p></div><span className={`claim-status claim-${c.status||"pending"}`}>{c.status||"pending"}</span></div>)}</div>:<EmptyState title="No claims yet">Claim requests you send will appear here.</EmptyState>}</section><section className="dashboard-section"><div className="section-heading"><div><span className="eyebrow">Received</span><h2>Claims on my listings</h2></div></div>{received.length?<div className="claim-list">{received.map(c=><div className="claim-row" key={c._id}><div><strong>{c.item?.title||"Item"}</strong><p>Claim from {c.claimant?.name||"Student"}</p></div><div className="claim-actions"><span className={`claim-status claim-${c.status||"pending"}`}>{c.status||"pending"}</span>{c.status==="pending"&&<><button className="button button-small" onClick={()=>update(c._id,"approved")}>Approve</button><button className="button button-small button-secondary" onClick={()=>update(c._id,"rejected")}>Reject</button></>}</div></div>)}</div>:<EmptyState title="No incoming claims">Requests from other students will appear here.</EmptyState>}</section></>}</div></section>;
}
